### ISSUE TITLE
Input Handler Error:  No input for desktop file path

### ISSUE THREAD

**Issue by nkovshov** [johannesjo/linux-window-session-manager#2]
Hi Johannes,
I've experienced some error with `lwsm`:
```
$ lwsm save
otherCmd: Generic Error 0
Input Handler Error:  No input for desktop file path
SAVED SESSION: DEFAULT
```
It appears when I try save session with opened google-chrome or atom editor.
I use `Ubuntu 16.04.02 LTS` and his `GNOME 3.18.5`.
I'd like to help you, so tell me what I can do to provide you more info about this error.

**Comment by johannesjo** [comment]
Thanks for reporting. I'll check this as soon as I can. May I ask what programs you have opened? Seems to be a special case to me. All the entries for that are in the https://github.com/johannesjo/linux-window-session-manager/blob/master/lib/default-config.js under `WM_CLASS_AND_EXECUTABLE_FILE_MAP` if you need a quick fix,

**Comment by nkovshov** [comment]
`google-chrome` and `atom` editor

**Comment by johannesjo** [comment]
Ok. It's not that, as it works fine with chrome and atom for me. Does it work for when you only have chrome OR atom opened?

Could you also maybe post the input of the `~/.lwsm/sessionData/DEFAULT.json` file? That would be helpful!

**Comment by nkovshov** [comment]
Strange, but now `lwsm save` doesn't throw this error and layout save/restore works fine, except some shift of `atom` window by Y-axis.
Yesterday I tried to reboot machine, but it didn't help me yesterday.
Saving only chrome and terminal windows or atom and terminal windows didn't work too.
I'm sorry, but I overrode json-file now, I'll post it if I stuck with this error again.

Thank you for this tool, it's really helpful.

**Comment by johannesjo** [comment]
I'm glad that it works for you now! Haven't found a good solution for the Y-axis problem unfortunately as it is a bug with x11 itself.

Keep me updated, if you encounter any further errors.

**Comment by eater** [comment]
I just installed lwsm and I am seeing this error as well, running several Chrome windows, Pale Moon, Gvim, and terminals.

**Comment by johannesjo** [comment]
Thanks for reporting! Pale Moon might be another exception. (See WM_CLASS_AND_EXECUTABLE_FILE_MAP in https://github.com/johannesjo/linux-window-session-manager/blob/master/lib/default-config.js). I'll check this on Monday.

**Comment by eater** [comment]
I think it's Chrome, and specifically Chrome [apps](https://chrome.google.com/webstore/category/apps?_feature=chromeapp). I get one "Generic Error" line for each Chrome app I have open.

**Comment by johannesjo** [comment]
@eater thanks for digging into this. I added a commit to support google chrome apps. Could you check again, please?

**Comment by eater** [comment]
Updated, and here's how it looks now:
```
$ lwsm save chromeapps                                                                                          
chrome-bikioccmkafdpakkkcpdbppfkghcmihk-Profile_1.desktop
chrome-kaoganeefjllmkgaaiddghcdejmncibh-Profile_1.desktop
chrome-mgiadchmmaobabcoknkoedjjdododcon-Profile_1.desktop
otherCmd: Generic Error 0
Input Handler Error:  No input for desktop file path
otherCmd: Generic Error 0
Input Handler Error:  No input for desktop file path
otherCmd: Generic Error 0
Input Handler Error:  No input for desktop file path
otherCmd: Generic Error 0
Input Handler Error:  No input for desktop file path
SAVED SESSION: chromeapps

$ lwsm restore chromeapps                                                                                       
xfce4-terminal.Xfce4-terminal is running:  true 3 0
Navigator.Pale moon is running:  true 1 0
google-chrome.Google-chrome is running:  true 1 0
crx_bikioccmkafdpakkkcpdbppfkghcmihk.Google-chrome is running:  false 1 0
crx_kaoganeefjllmkgaaiddghcdejmncibh.Google-chrome is running:  false 1 0
crx_mgiadchmmaobabcoknkoedjjdododcon.Google-chrome is running:  false 1 0
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn chrome-bikioccmkafdpakkkcpdbppfkghcmihk-Profile_1.desktop ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
```

**Comment by eater** [comment]
```
/home/eater/Desktop/chrome-bikioccmkafdpakkkcpdbppfkghcmihk-Default.desktop
/home/eater/.gnome/apps/chrome-bikioccmkafdpakkkcpdbppfkghcmihk-Default.desktop
/home/eater/.local/share/applications/chrome-bikioccmkafdpakkkcpdbppfkghcmihk-Default.desktop
```

**Comment by johannesjo** [comment]
Thank you! I published another patch. Could you please check another time if it now works for you?

**Comment by eater** [comment]
Hmm, now it's not showing the Input Handler Error but it's still not working:
```
$lwsm save chromeapps2
otherCmd: Generic Error 0
$lwsm restore chromeapps2
Generic Error in Main Handler [Error: could not load data]
```

**Comment by johannesjo** [comment]
This means that something is wrong with the data store... I'll added a new patch with better error reporting. It would be really nice if you could try it again.

Also deleting all config files might help (`~/.lwsm/**/*`) might help, in case something got messed up.

**Comment by eater** [comment]
I deleted all the config files and now I get the Input Handler error again, just once -- but save and restore works!

**Comment by johannesjo** [comment]
I'm happy that it works for you now. The input handler error occurs, when an application is saved, but no valid desktop file path is given. You can also fix this manually in `~/.lwsm/your-session-name.json.

Would be nice to have a better error handling though. I'll work on that.
