### ISSUE TITLE
Is that still supported? Doesn't work on 18.10 for me.

### ISSUE THREAD

**Issue by NinjaTurtle007** [johannesjo/linux-window-session-manager#43]
I updated it according to the instructions but doesn't work neither from the gnome extension or from the terminal.

Here is what trying to save a session outputs:

> ` lwsm save test1
sudo: unable to resolve host user: Invalid argument
0x2000097 has no wmClassName. Win:  { windowId: '0x2000097',
  windowIdDec: 33554583,
  states: [],
  wmType: '_NET_WM_WINDOW_TYPE_NORMAL' }
Generic Error in Meta Wrapper TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.basename (path.js:1380:5)
    at Promise (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:193:18)
    at new Promise (<anonymous>)
    at parseChromeAppDesktopFileName (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:190:10)
    at Promise (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:166:9)
    at new Promise (<anonymous>)
    at parseExecutableFileFromWmClassName (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:158:10)
    at promises.push (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:136:18)
    at <anonymous> TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.basename (path.js:1380:5)
    at Promise (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:193:18)
    at new Promise (<anonymous>)
    at parseChromeAppDesktopFileName (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:190:10)
    at Promise (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:166:9)
    at new Promise (<anonymous>)
    at parseExecutableFileFromWmClassName (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:158:10)
    at promises.push (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:136:18)
    at <anonymous>
Generic Error in Meta Wrapper TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.basename (path.js:1380:5)
    at Promise (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:193:18)
    at new Promise (<anonymous>)
    at parseChromeAppDesktopFileName (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:190:10)
    at Promise (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:166:9)
    at new Promise (<anonymous>)
    at parseExecutableFileFromWmClassName (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:158:10)
    at promises.push (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:136:18)
    at <anonymous> TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.basename (path.js:1380:5)
    at Promise (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:193:18)
    at new Promise (<anonymous>)
    at parseChromeAppDesktopFileName (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:190:10)
    at Promise (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:166:9)
    at new Promise (<anonymous>)
    at parseExecutableFileFromWmClassName (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:158:10)
    at promises.push (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:136:18)
    at <anonymous>
Generic Error in Meta Wrapper TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.basename (path.js:1380:5)
    at Promise (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:193:18)
    at new Promise (<anonymous>)
    at parseChromeAppDesktopFileName (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:190:10)
    at Promise (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:166:9)
    at new Promise (<anonymous>)
    at parseExecutableFileFromWmClassName (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:158:10)
    at promises.push (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:136:18)
    at <anonymous> TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.basename (path.js:1380:5)
    at Promise (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:193:18)
    at new Promise (<anonymous>)
    at parseChromeAppDesktopFileName (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:190:10)
    at Promise (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:166:9)
    at new Promise (<anonymous>)
    at parseExecutableFileFromWmClassName (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:158:10)
    at promises.push (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:136:18)
    at <anonymous>
(node:11729) UnhandledPromiseRejectionWarning: TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.basename (path.js:1380:5)
    at Promise (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:193:18)
    at new Promise (<anonymous>)
    at parseChromeAppDesktopFileName (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:190:10)
    at Promise (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:166:9)
    at new Promise (<anonymous>)
    at parseExecutableFileFromWmClassName (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:158:10)
    at promises.push (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:136:18)
    at <anonymous>
(node:11729) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:11729) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by johannesjo** [comment]
Thanks for reporting. This should hopefully be fixed now.

**Comment by NinjaTurtle007** [comment]
Yes indeed, it does work now but still throws out errors for widely useds apps like, telegram, keepassxc, calc, toggl, etc

Not sure why it struggles to find the desktop file for so many of them.

Here is an example of the error for one of the apps:


> `indDesktopFile cant find file; searched patterns []
util: Generic Error findDesktopFile cant find file; searched patterns undefined
util: [Arguments] { '0': 'findDesktopFile cant find file; searched patterns' }
Input Handler Error:  No input for desktop file path for window "telegram-desktop.TelegramDesktop". Please fix this manually in config file for this session in ~/.lwsm/{currentSessionName}.json

LWSM was unable to guess the location of your executable/desktop file.
`

**Comment by johannesjo** [comment]
Sorry for the very late reply. If notice any missing apps, it would be really cool if you could provide a PR to this file:
https://github.com/johannesjo/linux-window-session-manager/blob/master/src/defaultConfig.ts
